/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2024-03-09 10:38:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.net.URLEncoder;
import java.security.SecureRandom;
import java.math.BigInteger;

public final class Main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("jar:file:/C:/HotUdon/HotUdon/src/main/webapp/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("/WEB-INF/./parts/Info.jsp", Long.valueOf(1709980388718L));
    _jspx_dependants.put("/WEB-INF/./parts/./LoginModal.jsp", Long.valueOf(1709980388597L));
    _jspx_dependants.put("jar:file:/C:/HotUdon/HotUdon/src/main/webapp/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1709969718352L));
    _jspx_dependants.put("/WEB-INF/./parts/Nav.jsp", Long.valueOf(1709980388581L));
    _jspx_dependants.put("/WEB-INF/./parts/header.jsp", Long.valueOf(1709980388735L));
    _jspx_dependants.put("/WEB-INF/./parts/../user/kakaoLogin.jsp", Long.valueOf(1709969719019L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.security.SecureRandom");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.math.BigInteger");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<title>Insert title here</title>\n");
      out.write("	<style>\n");
      out.write("		#container {\n");
      out.write("			height: 100vh;\n");
      out.write("			width: 100vw;\n");
      out.write("			margin: 0;\n");
      out.write("			padding: 0;\n");
      out.write("			position: relative;\n");
      out.write("		}\n");
      out.write("		#main{\n");
      out.write("			height: 100%;\n");
      out.write("			width: 100%;\n");
      out.write("		}\n");
      out.write("		th, td{\n");
      out.write("			/* border: 1px solid black; */\n");
      out.write("		}\n");
      out.write("		#main > td, #main > td > th {\n");
      out.write("			border: 1px solid black;\n");
      out.write("		}\n");
      out.write("		#main_nav, #main_info {\n");
      out.write("			width: 300px;\n");
      out.write("		}\n");
      out.write("		#main_header{\n");
      out.write("			width: 1200px;\n");
      out.write("			height: 100px;\n");
      out.write("		}\n");
      out.write("	</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"container\">\n");
      out.write("	<table id=\"main\">\n");
      out.write("		<!-- Nav -->\n");
      out.write("		<tr id=\"main_tr\">\n");
      out.write("			<td id=\"main_nav\" rowspan =\"2\">\n");
      out.write("				");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#wrap{\r\n");
      out.write("	position: relative;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("#bar {\r\n");
      out.write("  width: 30px;\r\n");
      out.write("  height: 25px;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  right: -47px;\r\n");
      out.write("  top: 125px;\r\n");
      out.write("}\r\n");
      out.write("#catrgory_text{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  right: -147px;\r\n");
      out.write("  top: 95px;\r\n");
      out.write("  text-align: right;\r\n");
      out.write("  background-color: black;\r\n");
      out.write("  background-size: contain;\r\n");
      out.write("  padding: 10px 10px 10px 45px;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write(".bar1, .bar2, .bar3 {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 4px;\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  transition: transform 0.3s ease;\r\n");
      out.write("  z-index: 2;\r\n");
      out.write("}\r\n");
      out.write("#category {\r\n");
      out.write("  display: none; /* 초기에는 숨김 */\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 110px;\r\n");
      out.write("  right: 0px;\r\n");
      out.write("	width: 80%;\r\n");
      out.write("	background-color: #eee;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("#category .category {\r\n");
      out.write("	display: block;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("#category.open {\r\n");
      out.write("  display: block; /* h2 클릭시 나타나게 함 */\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("#bar.open .bar1 {\r\n");
      out.write("  transform: translateY(10px) rotate(45deg);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bar.open .bar2 {\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bar.open .bar3 {\r\n");
      out.write("  transform: translateY(-10px) rotate(-45deg);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("      <div id=\"bar\">\r\n");
      out.write("        <div class=\"bar1\"></div>\r\n");
      out.write("        <div class=\"bar2\"></div>\r\n");
      out.write("        <div class=\"bar3\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <h2 id=\"catrgory_text\">카테고리</h2>\r\n");
      out.write("      <div id=\"category\">\r\n");
      out.write("        <div class=\"category\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main.do'\">전체</div>\r\n");
      out.write("        <div class=\"category\">디지털</div>\r\n");
      out.write("        <div class=\"category\">의류</div>\r\n");
      out.write("        <div class=\"category\">가구</div>\r\n");
      out.write("        <div class=\"category\">기타</div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script>\r\n");
      out.write("var bar = document.getElementById(\"bar\");\r\n");
      out.write("var categoryText = document.getElementById(\"catrgory_text\");\r\n");
      out.write("\r\n");
      out.write("document.addEventListener(\"click\", function(event) {\r\n");
      out.write("  if (event.target === categoryText) {\r\n");
      out.write("    if (bar.classList.contains(\"open\")) {\r\n");
      out.write("      bar.classList.remove(\"open\");\r\n");
      out.write("      category.classList.remove(\"open\");\r\n");
      out.write("    } else {\r\n");
      out.write("      bar.classList.add(\"open\");\r\n");
      out.write("      category.classList.add(\"open\");\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\n");
      out.write("				");
      out.write("\n");
      out.write("			</td>\n");
      out.write("\n");
      out.write("			<!-- header -->\n");
      out.write("			<td id=\"main_header\" >\n");
      out.write("				");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    #header{\r\n");
      out.write("    	display: flex;\r\n");
      out.write("    	justify-content: space-between;\r\n");
      out.write("    }\r\n");
      out.write("	#header #logo{\r\n");
      out.write("		width: 10%;\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("	#header #search{\r\n");
      out.write("		width: 80%;\r\n");
      out.write("    	display: flex;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("	}\r\n");
      out.write("	#header #search .search{\r\n");
      out.write("		width: 500px;\r\n");
      out.write("		height: 50px;\r\n");
      out.write("    	text-align: center;\r\n");
      out.write("		border-radius: 25px;\r\n");
      out.write("		line-height: 100px;\r\n");
      out.write("	}\r\n");
      out.write("	#header #userImg{\r\n");
      out.write("		width: 10%;\r\n");
      out.write("		heigth: 100px;\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("    #logo img{\r\n");
      out.write("    	height: 100px;\r\n");
      out.write("    }\r\n");
      out.write("    #userImg img{\r\n");
      out.write("    	height: 100px;\r\n");
      out.write("    	width: 100px;\r\n");
      out.write("    	border-radius: 50%;\r\n");
      out.write("    	\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" 	<header id=\"header\">\r\n");
      out.write("		<div id=\"logo\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main.do'\"><img src=\"./img/ulogo.png\"> </div>\r\n");
      out.write("		<div id=\"search\">\r\n");
      out.write("			<input type=\"text\" class=\"search\" name=\"search\" placeholder=\"검색어를 입력하세요\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"userImg\"> \r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write(" 	</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"overlay hidden\" onclick=\"unclickLogin()\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- //네이버 로그인  -->    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	#modal_log{\r\n");
      out.write("		margin-left: 30px;\r\n");
      out.write("	}\r\n");
      out.write("	.modal_td{\r\n");
      out.write("		border: none;\r\n");
      out.write("	}\r\n");
      out.write("	#login,#join{\r\n");
      out.write("		border: none;\r\n");
      out.write("		background-color: #fff;\r\n");
      out.write("		style: none;\r\n");
      out.write("	}\r\n");
      out.write("	.underBar{\r\n");
      out.write("		border-bottom: 2px solid skyblue;\r\n");
      out.write("		/* background-color: skyblue; */\r\n");
      out.write("	}\r\n");
      out.write("	#modal_join{\r\n");
      out.write("		display: block;\r\n");
      out.write("	}\r\n");
      out.write("	#modal_login{\r\n");
      out.write("		display: none;\r\n");
      out.write("	}\r\n");
      out.write("	.modal{\r\n");
      out.write("    	/* border: 1px solid black; */\r\n");
      out.write("    	border-radius: 10px;\r\n");
      out.write("    	width: 400px;\r\n");
      out.write("     	height: 600px;\r\n");
      out.write("    	margin: auto;\r\n");
      out.write("    	text-align: center;\r\n");
      out.write("    	background-color: #fff;\r\n");
      out.write("    	position: absolute;\r\n");
      out.write("    	top: 50%;\r\n");
      out.write("    	left: 50%;\r\n");
      out.write("    	transform: translate(-50%, -50%);\r\n");
      out.write("    	visibility: visible;\r\n");
      out.write("    	opacity: 1;\r\n");
      out.write("    	z-index: 4;\r\n");
      out.write("    }\r\n");
      out.write("    .hidden{\r\n");
      out.write("    	visibility: hidden;\r\n");
      out.write("    	opacity: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .btn{\r\n");
      out.write("    	border: none;\r\n");
      out.write("    	width: 334px;\r\n");
      out.write("    	height: 48px;\r\n");
      out.write("    	border-radius: 5px;\r\n");
      out.write("    	margin: 10px auto;\r\n");
      out.write("    	display: flex;\r\n");
      out.write("    	justify-content: center;\r\n");
      out.write("    	align-items: center;\r\n");
      out.write("    	position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    .naver svg{\r\n");
      out.write("    	color: #00C73C;\r\n");
      out.write("    }\r\n");
      out.write("    .btn svg{\r\n");
      out.write("    	vertical-align: middle;\r\n");
      out.write("    	margin-right: 10px;\r\n");
      out.write("    	position: absolute;\r\n");
      out.write("  		left: 50px;\r\n");
      out.write("    }\r\n");
      out.write("    .kakao:hover{\r\n");
      out.write("    	background-color: #FEE500;\r\n");
      out.write("    }\r\n");
      out.write("    .naver:hover{\r\n");
      out.write("    	background-color: #00C73C;\r\n");
      out.write("    	color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    .naver:hover path{\r\n");
      out.write("    	fill: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    .google:hover{\r\n");
      out.write("    	background-color: #DB4437;\r\n");
      out.write("    	color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    .google:hover path{\r\n");
      out.write("    	fill: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    .email:hover{\r\n");
      out.write("    	background-color: #FFF;\r\n");
      out.write("    }\r\n");
      out.write("    p{\r\n");
      out.write("    	font-size: 0.8em;\r\n");
      out.write("    	margin: 20px 30px;\r\n");
      out.write("    }\r\n");
      out.write("    .overlay{\r\n");
      out.write("		background-color: #00000096;\r\n");
      out.write("		width: 100%;\r\n");
      out.write(" 		height: 100%;\r\n");
      out.write(" 		position: fixed;\r\n");
      out.write(" 		top: 0;\r\n");
      out.write(" 		left: 0;\r\n");
      out.write(" 		z-index: 3;\r\n");
      out.write(" 		/* opacity: 0; */\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"modal hidden\">\r\n");
      out.write("	<br>\r\n");
      out.write("	\r\n");
      out.write("	<h3>뜨끈한 우동에서 중고거래 시작하기</h3>\r\n");
      out.write("	<H4>간편하게 가입하고 상품을 거래하세요</H4>\r\n");
      out.write("	<br>\r\n");
      out.write("	<table id=\"modal_log\">\r\n");
      out.write("	<tr>\r\n");
      out.write("	<td class=\"modal_td login \"> <button id=\"login\" onclick=\"clickLoginBtn()\"> 로그인</button> </td>\r\n");
      out.write("	<td class=\"modal_td join underBar\"> <button id=\"join\" onclick=\"clickJoinBtn()\">회원가입</button> </td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<br>\r\n");
      out.write("		<button class=\"btn kakao\" onclick=\"kakaoLogin()\"");
      out.write(">\r\n");
      out.write("			<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"21\" height=\"21\" fill=\"#3C1E1E\" viewBox=\"0 0 21 21\">\r\n");
      out.write("			<path fill=\"current\" d=\"M10.5 3.217c4.514 0 8 2.708 8 6.004 0 3.758-4.045 6.184-8 5.892-1.321-.093-1.707-.17-2.101-.23-1.425.814-2.728 2.344-3.232 2.334-.325-.19.811-2.896.533-3.114-.347-.244-3.157-1.329-3.2-4.958 0-3.199 3.486-5.928 8-5.928Z\"></path>\r\n");
      out.write("			</svg> 카카오로 시작하기 </button>\r\n");
      out.write("		<button class=\"btn naver\" id=\"naverIdLogin_loginButton\" onclick=\"naverLogin()<!-- javascript:void(0) -->\"");
      out.write("> \r\n");
      out.write("			<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"21\" height=\"21\" fill=\"none\" viewBox=\"0 0 21 21\">\r\n");
      out.write("			<path fill=\"#00C73C\" d=\"M4 16.717h4.377V9.98l4.203 6.737H17v-13h-4.377v6.737l-4.16-6.737H4v13Z\"></path>\r\n");
      out.write("	     	</svg> 네이버로 시작하기 </button>\r\n");
      out.write("		<button id=\"GgCustomLogin\" class=\"btn google\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/googleLogin.do'\"> \r\n");
      out.write("			<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"21\" height=\"21\" fill=\"none\" viewBox=\"0 0 21 21\">\r\n");
      out.write("			<path fill=\"#4285F4\" d=\"M18.18 10.398c0-.567-.05-1.113-.145-1.636H10.5v3.094h4.306a3.68 3.68 0 0 1-1.597 2.415v2.007h2.586c1.512-1.393 2.385-3.443 2.385-5.88Z\"></path>\r\n");
      out.write("	  		<path fill=\"#34A853\" d=\"M10.5 18.216c2.16 0 3.97-.716 5.294-1.938l-2.585-2.007c-.717.48-1.633.763-2.71.763-2.083 0-3.847-1.407-4.476-3.298H3.351v2.073a7.997 7.997 0 0 0 7.149 4.407Z\"></path>\r\n");
      out.write("			<path fill=\"#FBBC05\" d=\"M6.024 11.738c-.16-.48-.251-.993-.251-1.52 0-.528.09-1.04.25-1.52V6.625H3.352a7.997 7.997 0 0 0-.851 3.593c0 1.29.31 2.512.85 3.592l2.674-2.072Z\"></path>\r\n");
      out.write("			<path fill=\"#EA4335\" d=\"M10.5 5.399c1.174 0 2.229.403 3.058 1.196L15.852 4.3c-1.385-1.29-3.196-2.083-5.352-2.083a7.997 7.997 0 0 0-7.15 4.407l2.673 2.073c.63-1.891 2.393-3.298 4.477-3.298Z\"></path>\r\n");
      out.write("			</svg> 구글로 시작하기 </button>\r\n");
      out.write("		<br>	\r\n");
      out.write("	   \r\n");
      out.write("	<div id=\"modal_join\">\r\n");
      out.write("	    <button class=\"btn email\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/selfJoin.do'\" >\r\n");
      out.write("    	<svg stroke=\"currentColor\" fill=\"currentColor\" stroke-width=\"0\" viewBox=\"0 0 16 16\" class=\"text-sm sm:text-base me-1.5\" height=\"1em\" width=\"1em\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("		<path fill-rule=\"evenodd\" d=\"M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 100-6 3 3 0 000 6z\" clip-rule=\"evenodd\"></path>\r\n");
      out.write("		</svg> 이메일로 시작하기 </button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"modal_login\">\r\n");
      out.write("	    <button class=\"btn email\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/selfLogin.do'\" >\r\n");
      out.write("    	<svg stroke=\"currentColor\" fill=\"currentColor\" stroke-width=\"0\" viewBox=\"0 0 16 16\" class=\"text-sm sm:text-base me-1.5\" height=\"1em\" width=\"1em\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("		<path fill-rule=\"evenodd\" d=\"M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 100-6 3 3 0 000 6z\" clip-rule=\"evenodd\"></path>\r\n");
      out.write("		</svg> 이메일로 로그인하기 </button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br><hr width=\"350px\"><br>	\r\n");
      out.write("	<p> 도움이 필요하시면 고객센터 또는 02-000-0000으로 문의 주시기 바랍니다.</p>	                                                                              \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  const $btn = document.querySelector(\".userImg\");\r\n");
      out.write("  const $modal = document.querySelector(\".modal\");\r\n");
      out.write("  const $overlay = document.querySelector(\".overlay\");\r\n");
      out.write("		\r\n");
      out.write("	function clickLogin(){\r\n");
      out.write("		$modal.classList.remove(\"hidden\");\r\n");
      out.write("		$overlay.classList.remove(\"hidden\");\r\n");
      out.write("	}\r\n");
      out.write("	 function unclickLogin(){\r\n");
      out.write("	    $modal.classList.add(\"hidden\");\r\n");
      out.write("	    $overlay.classList.add(\"hidden\");\r\n");
      out.write("	    $cash.classList.add(\"hidden\");\r\n");
      out.write("	 }\r\n");
      out.write("	let $kakao = document.querySelector(\".kakao\");			  \r\n");
      out.write("	let $naver = document.querySelector(\".naver\");			  \r\n");
      out.write("	let $google = document.querySelector(\".google\");			  \r\n");
      out.write("	let $email = document.querySelector(\".email\");	\r\n");
      out.write("	let $join = document.querySelector(\".join\"); 	\r\n");
      out.write("	let $login = document.querySelector(\".login\"); 	\r\n");
      out.write("	\r\n");
      out.write("	function clickLoginBtn(){\r\n");
      out.write(" 		$kakao.innerHTML = '<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"21\" height=\"21\" fill=\"#3C1E1E\" viewBox=\"0 0 21 21\"><path fill=\"current\" d=\"M10.5 3.217c4.514 0 8 2.708 8 6.004 0 3.758-4.045 6.184-8 5.892-1.321-.093-1.707-.17-2.101-.23-1.425.814-2.728 2.344-3.232 2.334-.325-.19.811-2.896.533-3.114-.347-.244-3.157-1.329-3.2-4.958 0-3.199 3.486-5.928 8-5.928Z\"></path></svg>카카오로 로그인하기';\r\n");
      out.write("		$naver.innerHTML = '<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"21\" height=\"21\" fill=\"none\" viewBox=\"0 0 21 21\"><path fill=\"#00C73C\" d=\"M4 16.717h4.377V9.98l4.203 6.737H17v-13h-4.377v6.737l-4.16-6.737H4v13Z\"></path></svg> 네이버로 로그인하기';\r\n");
      out.write("		$google.innerHTML = '<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"21\" height=\"21\" fill=\"none\" viewBox=\"0 0 21 21\"><path fill=\"#4285F4\" d=\"M18.18 10.398c0-.567-.05-1.113-.145-1.636H10.5v3.094h4.306a3.68 3.68 0 0 1-1.597 2.415v2.007h2.586c1.512-1.393 2.385-3.443 2.385-5.88Z\"></path><path fill=\"#34A853\" d=\"M10.5 18.216c2.16 0 3.97-.716 5.294-1.938l-2.585-2.007c-.717.48-1.633.763-2.71.763-2.083 0-3.847-1.407-4.476-3.298H3.351v2.073a7.997 7.997 0 0 0 7.149 4.407Z\"></path><path fill=\"#FBBC05\" d=\"M6.024 11.738c-.16-.48-.251-.993-.251-1.52 0-.528.09-1.04.25-1.52V6.625H3.352a7.997 7.997 0 0 0-.851 3.593c0 1.29.31 2.512.85 3.592l2.674-2.072Z\"></path><path fill=\"#EA4335\" d=\"M10.5 5.399c1.174 0 2.229.403 3.058 1.196L15.852 4.3c-1.385-1.29-3.196-2.083-5.352-2.083a7.997 7.997 0 0 0-7.15 4.407l2.673 2.073c.63-1.891 2.393-3.298 4.477-3.298Z\"></path></svg> 구글로 로그인하기';\r\n");
      out.write("		$email.innerHTML = '<svg stroke=\"currentColor\" fill=\"currentColor\" stroke-width=\"0\" viewBox=\"0 0 16 16\" class=\"text-sm sm:text-base me-1.5\" height=\"1em\" width=\"1em\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" d=\"M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 100-6 3 3 0 000 6z\" clip-rule=\"evenodd\"></path></svg> 이메일로 로그인하기';\r\n");
      out.write("  		$join.classList.remove(\"underBar\");\r\n");
      out.write("  		$login.classList.add(\"underBar\");\r\n");
      out.write("  		document.getElementById(\"modal_join\").style.display = \"none\";\r\n");
      out.write("  		document.getElementById(\"modal_login\").style.display = \"block\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function clickJoinBtn(){\r\n");
      out.write(" 		$kakao.innerHTML = '<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"21\" height=\"21\" fill=\"#3C1E1E\" viewBox=\"0 0 21 21\"><path fill=\"current\" d=\"M10.5 3.217c4.514 0 8 2.708 8 6.004 0 3.758-4.045 6.184-8 5.892-1.321-.093-1.707-.17-2.101-.23-1.425.814-2.728 2.344-3.232 2.334-.325-.19.811-2.896.533-3.114-.347-.244-3.157-1.329-3.2-4.958 0-3.199 3.486-5.928 8-5.928Z\"></path></svg> 카카오로 시작하기';\r\n");
      out.write("		$naver.innerHTML = '<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"21\" height=\"21\" fill=\"none\" viewBox=\"0 0 21 21\"><path fill=\"#00C73C\" d=\"M4 16.717h4.377V9.98l4.203 6.737H17v-13h-4.377v6.737l-4.16-6.737H4v13Z\"></path></svg> 네이버로 시작하기';\r\n");
      out.write("		$google.innerHTML = '<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"21\" height=\"21\" fill=\"none\" viewBox=\"0 0 21 21\"><path fill=\"#4285F4\" d=\"M18.18 10.398c0-.567-.05-1.113-.145-1.636H10.5v3.094h4.306a3.68 3.68 0 0 1-1.597 2.415v2.007h2.586c1.512-1.393 2.385-3.443 2.385-5.88Z\"></path><path fill=\"#34A853\" d=\"M10.5 18.216c2.16 0 3.97-.716 5.294-1.938l-2.585-2.007c-.717.48-1.633.763-2.71.763-2.083 0-3.847-1.407-4.476-3.298H3.351v2.073a7.997 7.997 0 0 0 7.149 4.407Z\"></path><path fill=\"#FBBC05\" d=\"M6.024 11.738c-.16-.48-.251-.993-.251-1.52 0-.528.09-1.04.25-1.52V6.625H3.352a7.997 7.997 0 0 0-.851 3.593c0 1.29.31 2.512.85 3.592l2.674-2.072Z\"></path><path fill=\"#EA4335\" d=\"M10.5 5.399c1.174 0 2.229.403 3.058 1.196L15.852 4.3c-1.385-1.29-3.196-2.083-5.352-2.083a7.997 7.997 0 0 0-7.15 4.407l2.673 2.073c.63-1.891 2.393-3.298 4.477-3.298Z\"></path></svg> 구글로 시작하기';\r\n");
      out.write("		$email.innerHTML = '<svg stroke=\"currentColor\" fill=\"currentColor\" stroke-width=\"0\" viewBox=\"0 0 16 16\" class=\"text-sm sm:text-base me-1.5\" height=\"1em\" width=\"1em\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" d=\"M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 100-6 3 3 0 000 6z\" clip-rule=\"evenodd\"></path></svg> 이메일로 시작하기';\r\n");
      out.write("  		$join.classList.add(\"underBar\");\r\n");
      out.write("  		$login.classList.remove(\"underBar\");\r\n");
      out.write("  		document.getElementById(\"modal_join\").style.display = \"block\";\r\n");
      out.write("  		document.getElementById(\"modal_login\").style.display = \"none\";\r\n");
      out.write("	}\r\n");
      out.write("	function naverLogin(){\r\n");
      out.write("		fetch(\"naverLogin.do\", {\r\n");
      out.write("			method : \"POST\",\r\n");
      out.write("			headers : {\"Content-Type\": \"application/x-www-form-urlencoded; charset=UTF-8\",},\r\n");
      out.write("			/* body : \"id=\"+id.value.trim(), */\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		.then(response => response.text())\r\n");
      out.write("		.then(getResult)\r\n");
      out.write("		.catch(error => console.log(error));\r\n");
      out.write("		\r\n");
      out.write("		function getResult(apiURL) {\r\n");
      out.write("			location.href=apiURL;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 카카오 스크립트 -->\r\n");
      out.write("<script src=\"https://developers.kakao.com/sdk/js/kakao.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("Kakao.init('00ad72e29796cba962a38d1cdb07c5e5'); //발급받은 키 중 javascript키를 사용해준다.\r\n");
      out.write("Kakao.isInitialized(); // sdk초기화여부판단\r\n");
      out.write("kakaoLogout();\r\n");
      out.write("//카카오로그인\r\n");
      out.write("function kakaoLogin() {\r\n");
      out.write("    Kakao.Auth.login({\r\n");
      out.write("        success: function (response) {\r\n");
      out.write("            Kakao.API.request({\r\n");
      out.write("                url: '/v2/user/me',\r\n");
      out.write("                success: function (response) {\r\n");
      out.write("                    console.log(response);\r\n");
      out.write("\r\n");
      out.write("                    fetch(\"kakaoLogin.do\", {\r\n");
      out.write("                        method: \"POST\",\r\n");
      out.write("                        headers: {\"Content-Type\": \"application/x-www-form-urlencoded; charset=UTF-8\"},\r\n");
      out.write("                        body: \"id=\" + response['id']+\"&nickname=\"+response.properties.nickname,\r\n");
      out.write("                    })\r\n");
      out.write("                    .then(response => {\r\n");
      out.write("                        // 요청 성공 시 처리할 코드\r\n");
      out.write("                        console.log(\"요청 성공:\", response);\r\n");
      out.write("                    })\r\n");
      out.write("                    .then(getResult)\r\n");
      out.write("                    .catch(error => {\r\n");
      out.write("                        // 요청 실패 시 처리할 코드\r\n");
      out.write("                        console.error(\"요청 실패:\", error);\r\n");
      out.write("                    });\r\n");
      out.write("                    \r\n");
      out.write("                    function getResult(nextPage) {\r\n");
      out.write("            			location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main.do\";\r\n");
      out.write("            		}\r\n");
      out.write("                },\r\n");
      out.write("                fail: function (error) {\r\n");
      out.write("                    // Kakao.API.request 요청 실패 시 처리할 코드\r\n");
      out.write("                    console.error(\"Kakao.API.request 요청 실패:\", error);\r\n");
      out.write("                },\r\n");
      out.write("            });\r\n");
      out.write("        },\r\n");
      out.write("        fail: function (error) {\r\n");
      out.write("            // Kakao.Auth.login 요청 실패 시 처리할 코드\r\n");
      out.write("            console.error(\"Kakao.Auth.login 요청 실패:\", error);\r\n");
      out.write("        },\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("//카카오로그아웃  \r\n");
      out.write("function kakaoLogout() {\r\n");
      out.write("\r\n");
      out.write("	if (Kakao.Auth.getAccessToken()) {\r\n");
      out.write("      Kakao.API.request({\r\n");
      out.write("        url: '/v1/user/unlink',\r\n");
      out.write("        success: function (response) {\r\n");
      out.write("        	console.log(response)\r\n");
      out.write("        },\r\n");
      out.write("        fail: function (error) {\r\n");
      out.write("          console.log(error)\r\n");
      out.write("        },\r\n");
      out.write("      })\r\n");
      out.write("      Kakao.Auth.setAccessToken(undefined)\r\n");
      out.write("    }\r\n");
      out.write("	\r\n");
      out.write("  }  \r\n");
      out.write("</script>\r\n");
      out.write("<!-- 	<script src=\"https://developers.kakao.com/sdk/js/kakao.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		//	00ad72e29796cba962a38d1cdb07c5e5\r\n");
      out.write("		window.Kakao.init(\"00ad72e29796cba962a38d1cdb07c5e5\");\r\n");
      out.write("		\r\n");
      out.write("		function kakaoLogin(){\r\n");
      out.write("			window.Kakao.Auth.login({\r\n");
      out.write("				scope:'profile_nickname, profile_image',\r\n");
      out.write("				success: function(authObj){\r\n");
      out.write("					console.log(authObj);\r\n");
      out.write("					window.Kakao.API.request({\r\n");
      out.write("						url:'/v2/user/me',\r\n");
      out.write("						success: res =>{\r\n");
      out.write("							const kakao_account = res.kakao_account;\r\n");
      out.write("							console.log(kakao_account);\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function kakaoLogout() {\r\n");
      out.write("		    if (Kakao.Auth.getAccessToken()) {\r\n");
      out.write("		      Kakao.API.request({\r\n");
      out.write("		        url: '/v1/user/unlink',\r\n");
      out.write("		        success: function (response) {\r\n");
      out.write("		        	console.log(response)\r\n");
      out.write("		        },\r\n");
      out.write("		        fail: function (error) {\r\n");
      out.write("		          console.log(error)\r\n");
      out.write("		        },\r\n");
      out.write("		      })\r\n");
      out.write("		      Kakao.Auth.setAccessToken(undefined)\r\n");
      out.write("		    }\r\n");
      out.write("		  }  -->\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("				");
      out.write("\n");
      out.write("			</td>\n");
      out.write("\n");
      out.write("			<!-- Info -->\n");
      out.write("			<td id=\"main_info\" rowspan =\"2\">\n");
      out.write("				");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(" 	.info{\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		visibility: visible;\r\n");
      out.write("    	opacity: 1;\r\n");
      out.write("    	position: relative;\r\n");
      out.write("	}\r\n");
      out.write("	.hidden{\r\n");
      out.write("		visibility: hidden;\r\n");
      out.write("    	opacity: 0;\r\n");
      out.write("	}\r\n");
      out.write("	.info #myPage{\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		top: 0px;\r\n");
      out.write("		left: 150px;\r\n");
      out.write("		border: none;\r\n");
      out.write("		width: 100px;\r\n");
      out.write("		height: 40px;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	.info #myPage:hover{\r\n");
      out.write("		background-color: #bbb;\r\n");
      out.write("	}\r\n");
      out.write("	.info_nickname{\r\n");
      out.write("		text-decoration: none;\r\n");
      out.write("      	color: black;\r\n");
      out.write("	}\r\n");
      out.write("	.info_cash{}\r\n");
      out.write("	.info_notify{\r\n");
      out.write("		width: 95%;\r\n");
      out.write("		height: 500px;\r\n");
      out.write("		border: 1px solid black;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("		margin: 10px 0;\r\n");
      out.write("	}\r\n");
      out.write("	.btns{\r\n");
      out.write("		width: 95%;\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("		margin: 10px 0;\r\n");
      out.write("		padding: 10px auto;\r\n");
      out.write("		border: none;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("		font-size: 1.5em;\r\n");
      out.write("	}\r\n");
      out.write("	.btns:hover {\r\n");
      out.write("		background-color: #bbb;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"info hidden\">\r\n");
      out.write(" 	<a class=\"info_nickname\" href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/userMyPage.do?no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ user.no }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\'');
      out.write('>');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ user.nickname }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('(');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ user.name }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") </a>\r\n");
      out.write(" 	<div class=\"info_cash\" onclick=\"\"> 보유 캐시 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ user.cash }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </div>\r\n");
      out.write(" 	<input type=\"button\" id=\"myPage\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/userMyPage.do?no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ user.no }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\" value=\"마이페이지\"/>\r\n");
      out.write(" 	<div class=\"info_notify\" > 알림 </div>\r\n");
      out.write(" 	<button class=\"btns info_chat\" onclick=\"\">채팅</button>\r\n");
      out.write(" 	<button class=\"btns info_pay\" onclick=\"\">결제</button>\r\n");
      out.write(" 	<button class=\"btns info_quick\" onclick=\"location.href=`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/quickMain.do?no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.no}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`\">퀵 서비스</button>\r\n");
      out.write(" 	<input type=\"button\" class=\"btns info_logout\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/userLogOut.do'\" value=\"로그아웃\"/>\r\n");
      out.write(" </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 카카오 스크립트 -->\r\n");
      out.write("<script src=\"https://developers.kakao.com/sdk/js/kakao.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("Kakao.init('00ad72e29796cba962a38d1cdb07c5e5'); //발급받은 키 중 javascript키를 사용해준다.\r\n");
      out.write("Kakao.isInitialized(); // sdk초기화여부판단\r\n");
      out.write("kakaoLogout();\r\n");
      out.write("//카카오로그인\r\n");
      out.write("function kakaoLogin() {\r\n");
      out.write("    Kakao.Auth.login({\r\n");
      out.write("        success: function (response) {\r\n");
      out.write("            Kakao.API.request({\r\n");
      out.write("                url: '/v2/user/me',\r\n");
      out.write("                success: function (response) {\r\n");
      out.write("                    console.log(response);\r\n");
      out.write("\r\n");
      out.write("                    fetch(\"kakaoLogin.do\", {\r\n");
      out.write("                        method: \"POST\",\r\n");
      out.write("                        headers: {\"Content-Type\": \"application/x-www-form-urlencoded; charset=UTF-8\"},\r\n");
      out.write("                        body: \"id=\" + response['id']+\"&nickname=\"+response.properties.nickname,\r\n");
      out.write("                    })\r\n");
      out.write("                    .then(response => {\r\n");
      out.write("                        // 요청 성공 시 처리할 코드\r\n");
      out.write("                        console.log(\"요청 성공:\", response);\r\n");
      out.write("                    })\r\n");
      out.write("                    .then(getResult)\r\n");
      out.write("                    .catch(error => {\r\n");
      out.write("                        // 요청 실패 시 처리할 코드\r\n");
      out.write("                        console.error(\"요청 실패:\", error);\r\n");
      out.write("                    });\r\n");
      out.write("                    \r\n");
      out.write("                    function getResult(nextPage) {\r\n");
      out.write("            			location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main.do\";\r\n");
      out.write("            		}\r\n");
      out.write("                },\r\n");
      out.write("                fail: function (error) {\r\n");
      out.write("                    // Kakao.API.request 요청 실패 시 처리할 코드\r\n");
      out.write("                    console.error(\"Kakao.API.request 요청 실패:\", error);\r\n");
      out.write("                },\r\n");
      out.write("            });\r\n");
      out.write("        },\r\n");
      out.write("        fail: function (error) {\r\n");
      out.write("            // Kakao.Auth.login 요청 실패 시 처리할 코드\r\n");
      out.write("            console.error(\"Kakao.Auth.login 요청 실패:\", error);\r\n");
      out.write("        },\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("//카카오로그아웃  \r\n");
      out.write("function kakaoLogout() {\r\n");
      out.write("\r\n");
      out.write("	if (Kakao.Auth.getAccessToken()) {\r\n");
      out.write("      Kakao.API.request({\r\n");
      out.write("        url: '/v1/user/unlink',\r\n");
      out.write("        success: function (response) {\r\n");
      out.write("        	console.log(response)\r\n");
      out.write("        },\r\n");
      out.write("        fail: function (error) {\r\n");
      out.write("          console.log(error)\r\n");
      out.write("        },\r\n");
      out.write("      })\r\n");
      out.write("      Kakao.Auth.setAccessToken(undefined)\r\n");
      out.write("    }\r\n");
      out.write("	\r\n");
      out.write("  }  \r\n");
      out.write("</script>\r\n");
      out.write("<!-- 	<script src=\"https://developers.kakao.com/sdk/js/kakao.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		//	00ad72e29796cba962a38d1cdb07c5e5\r\n");
      out.write("		window.Kakao.init(\"00ad72e29796cba962a38d1cdb07c5e5\");\r\n");
      out.write("		\r\n");
      out.write("		function kakaoLogin(){\r\n");
      out.write("			window.Kakao.Auth.login({\r\n");
      out.write("				scope:'profile_nickname, profile_image',\r\n");
      out.write("				success: function(authObj){\r\n");
      out.write("					console.log(authObj);\r\n");
      out.write("					window.Kakao.API.request({\r\n");
      out.write("						url:'/v2/user/me',\r\n");
      out.write("						success: res =>{\r\n");
      out.write("							const kakao_account = res.kakao_account;\r\n");
      out.write("							console.log(kakao_account);\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function kakaoLogout() {\r\n");
      out.write("		    if (Kakao.Auth.getAccessToken()) {\r\n");
      out.write("		      Kakao.API.request({\r\n");
      out.write("		        url: '/v1/user/unlink',\r\n");
      out.write("		        success: function (response) {\r\n");
      out.write("		        	console.log(response)\r\n");
      out.write("		        },\r\n");
      out.write("		        fail: function (error) {\r\n");
      out.write("		          console.log(error)\r\n");
      out.write("		        },\r\n");
      out.write("		      })\r\n");
      out.write("		      Kakao.Auth.setAccessToken(undefined)\r\n");
      out.write("		    }\r\n");
      out.write("		  }  -->\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	const $info = document.querySelector(\".info\");\r\n");
      out.write("	let clicked = false;\r\n");
      out.write("	function openInfo(){\r\n");
      out.write("		if(!clicked) {\r\n");
      out.write("			$info.classList.remove(\"hidden\");\r\n");
      out.write("			clicked = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$info.classList.add(\"hidden\");\r\n");
      out.write("			clicked = false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("</script>");
      out.write("\n");
      out.write("				");
      out.write("\n");
      out.write("			</td>\n");
      out.write("		</tr>\n");
      out.write("\n");
      out.write("		<!-- center -->\n");
      out.write("		<tr><td>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/Main.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /WEB-INF/Main.jsp(6,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/Main.jsp(6,0) '${ pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/./parts/header.jsp(54,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ user eq null }", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <a onclick=\"clickLogin()\"> <img class=\"userImg\" src=\"https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg\" ></a>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/./parts/header.jsp(55,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ user ne null }", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <a onclick=\"openInfo()\"> <img class=\"userImg\" src=\"./img/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ user.imgUrl }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" ></a>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
